canal:
  client:
    instances:
      example:
        batchSize: 1000
        host: 192.168.31.6
        port: 11111
spring:
  rabbitmq:
    host: 192.168.31.6
  output:
    ansi:
      enabled: always

